language: cpp

# Cache Ubuntu apt packages.
cache: apt

# Use Ubuntu trusty
sudo: required
dist: trusty

# Use container
#sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test # gcc/g++ 5.x
    packages:
    - gcc-5
    - g++-5
    - libgd2-noxpm-dev
    - libwxgtk2.8-dev

before_script:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next
  - sudo apt-get update -q
  - sudo apt-get install -y cmake-data cmake
  - sudo apt-get install -y ffmpeg libx265 libavcodec-ffmpeg-dev libavdevice-ffmpeg-dev libavfilter-ffmpeg-dev libavformat-ffmpeg-dev libavresample-ffmpeg-dev libavutil-ffmpeg-dev libswresample-ffmpeg-dev libswscale-ffmpeg-dev
  - export NUM_THREADS=4
  - export OMP_NUM_THREADS=4
  - export SCRIPTS=./scripts/

script: bash $SCRIPTS/travis_build_and_test.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.
  email:
    on_success: always
    on_failure: always
