language: cpp

# Cache Ubuntu apt packages.
cache: apt

# Use Ubuntu trusty
#sudo: required
#dist: trusty

# Use container
sudo: false

addons:
  apt:
    packages:
    - cmake
    - gcc
    - g++
    - clang
    - libswscale2
    - libswscale-dev
    - ffmpeg
    - libavdevice-dev
    - libavcodec-dev
    - libavfilter-dev
    - libavformat-dev
#   - libavresample-dev
    - libavutil-dev
    - libgd2-noxpm-dev
    - libwxgtk2.8-dev

#before_install:
# - sudo apt-get -qq update
#  - export NUM_THREADS=4
#  - export SCRIPTS=./scripts/

#install:
# - sudo -E $SCRIPTS/travis_install.sh

#before_script:
#  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64

script: $SCRIPTS/travis_build_and_test.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.
  email:
    on_success: always
    on_failure: always
