language: cpp

compiler:
  - clang
  - gcc

# Cache Ubuntu apt packages.
cache: apt

# Use Ubuntu trusty
sudo: required
dist: trusty

# Use container
#sudo: false

addons:
  apt:
    sources:
    #- george-edison55-precise-backports # cmake 3.x
    - ubuntu-toolchain-r-test # gcc/g++ 5.x
    packages:
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - clang
    - libswscale2
    - libswscale-dev
    - libavdevice-dev
    - libavcodec-dev
    - libavfilter-dev
    - libavformat-dev
#   - libavresample-dev
    - libavutil-dev
    - libgd2-noxpm-dev
    - libwxgtk2.8-dev

before_script:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -q
  - sudo apt-get install -y cmake-data cmake
  - export NUM_THREADS=4
  - export OMP_NUM_THREADS=4
  - export SCRIPTS=./scripts/

script: $SCRIPTS/travis_build_and_test.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.
  email:
    on_success: always
    on_failure: always
